apiVersion : apps/v1
kind: Deployment
metadata:
  name: pythonapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp 
          image: {{ .Values.imageTag }}
          resources:
            requests:
              memory: "100M"
              cpu: "50m"
            limits:
              memory: "200M"
              cpu: "70m"
          ports:
          - containerPort: 80
          envFrom:
          - secretRef:
              name: pythonapp-env
