name: "Deploy Python app to AKS cluster"
on:
  workflow_dispatch:
  push:
    # run on push to master
    branches:
      - main
jobs:
  Deploy_Python_app_to_AKS_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            osygroup.azurecr.io/pythonapp
          tags: |
            type=sha
            #type=sha,format=long
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ACR 
        uses: docker/login-action@v1
        with:
          registry: osygroup.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
          
          
      - name: Deploy to AKS
        run: |
          # Az Login
          az login --service-principal -u ${{ secrets.SP_USERNAME }} -p ${{ secrets.SP_PASSWORD }} --tenant ${{ secrets.AZ_TENANT }}
          # Connect to k8s
          az account set --subscription ${{ secrets.AZ_SUBSCRIPTION }}
          az aks get-credentials --resource-group AKSdemoRG --name AKSCluster
          
          # Create namespace if not created
          kubectl get namespace -oname | grep "namespace/pythonapp" \
                || kubectl create namespace pythonapp
                 
          # Helm Install chart
          helm upgrade --install pythonapp pythonapp_chart/ --namespace pythonapp --set imageTag=${{ steps.meta.outputs.tags }}

