name: "Deploy app to k8s cluster"
on:
  workflow_dispatch:
  push:
    # run on push to master
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            osygroup.azurecr.io/pythonapp
          tags: |
            type=sha
            #type=sha,format=long
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ACR 
        uses: docker/login-action@v1
        with:
          registry: osygroup.azurecr.io
          username: osygroup
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
